name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4.1.1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf

      - name: Config git
        run: |
            git config --global --add safe.directory $(realpath .)
            git checkout main

      - uses: EndBug/add-and-commit@v9
        with:
          add: main.pdf
          author_name: Latex Compiler
          author_email: noreplay@users.noreply.github.com
          message: Automatically updating the CV

      - name: Deploy to Github Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: root
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
